export const MDVP_FIELDS=['F0','Fhi','Flo','STD','Jita','Jitt','RAP','PPQ','sPPQ','vF0','ShdB','Shim','APQ','sAPQ','vAm','NHR'];

function finite(x){return Number.isFinite(Number(x))}
export function pairRows(rows, sampleKey='sample_id'){return rows.filter(r=>r?.[sampleKey]!=null).map(r=>({...r,[sampleKey]:String(r[sampleKey])}))}
export function paired(phona,mdvp,sampleKey='sample_id'){const p=new Map(pairRows(phona,sampleKey).map(r=>[r[sampleKey],r]));return pairRows(mdvp,sampleKey).filter(r=>p.has(r[sampleKey])).map(r=>({sample_id:r[sampleKey],phona:p.get(r[sampleKey]),mdvp:r}));}
export function mean(a){return a.length?a.reduce((s,x)=>s+x,0)/a.length:null}
export function sd(a){if(a.length<2)return 0;const m=mean(a);return Math.sqrt(a.reduce((s,x)=>s+(x-m)**2,0)/(a.length-1))}
export function correlation(a,b){const x=[],y=[];for(let i=0;i<a.length;i++)if(finite(a[i])&&finite(b[i])){x.push(Number(a[i]));y.push(Number(b[i]))}if(x.length<2)return null;const mx=mean(x),my=mean(y);let n=0,dx=0,dy=0;for(let i=0;i<x.length;i++){n+=(x[i]-mx)*(y[i]-my);dx+=(x[i]-mx)**2;dy+=(y[i]-my)**2}return dx&&dy?n/Math.sqrt(dx*dy):null}
export function parameterStats(pairs,field,phonaField=field){const diffs=[],abs=[],sq=[],x=[],y=[];for(const q of pairs){const a=Number(q.phona?.[phonaField]),b=Number(q.mdvp?.[field]);if(finite(a)&&finite(b)){x.push(a);y.push(b);const d=a-b;diffs.push(d);abs.push(Math.abs(d));sq.push(d*d)}}if(!diffs.length)return {parameter:field,n:0,phonaMean:null,mdvpMean:null,bias:null,mae:null,rmse:null,correlation:null,loa:null};const bias=mean(diffs),s=sd(diffs);return {parameter:field,n:diffs.length,phonaMean:mean(x),mdvpMean:mean(y),bias,mae:mean(abs),rmse:Math.sqrt(mean(sq)),correlation:correlation(x,y),loa:{lower:bias-1.96*s,upper:bias+1.96*s}}}
export function validationReport(pairs,mapping=MDVP_FIELDS.map(x=>({mdvp:x,phonacore:x}))){return {generatedAt:new Date().toISOString(),pairedSamples:pairs.length,parameters:mapping.map(m=>parameterStats(pairs,m.mdvp,m.phonacore)),note:'Agreement statistics do not establish clinical equivalence. Parameter definitions and MDVP settings must be matched before interpretation.'}}
export function blandAltmanPoints(pairs,field,phonaField=field){return pairs.map(q=>{const a=Number(q.phona?.[phonaField]),b=Number(q.mdvp?.[field]);return finite(a)&&finite(b)?{mean:(a+b)/2,difference:a-b}:null}).filter(Boolean)}
